import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { MODALIDADES, kitsForModalidadeLabel } from "@/data/kits";
import { emptyKit, kitLabels, buildEnderecoCompleto, countItensPendentes, BALAO_OPTIONS, HORARIO_AVISO, type StoredOrder, type ContractDetails, type KitChecklist } from "@/lib/orders-storage";
import { updateOrderOnSheet, fetchOrdersFromSheet, fetchOrderByIdPublic } from "@/lib/sheets-api";
import { mergePlanejamento } from "@/lib/planejamento-sync";
import { parseItensComprar, stringifyItensComprar, parseItensProduzir, stringifyItensProduzir, garantirMateriais, seedCatalogo } from "@/lib/materiais-catalogo";
import { sincronizarItensContrato, getOrdensLocal, compraStatusOf } from "@/lib/producao-api";
import { mudarEtapaCompra } from "@/lib/compras-flow";
import { ItensComprarEditor } from "@/components/itens-comprar-editor";
import { ItensProduzirEditor } from "@/components/itens-produzir-editor";
import { BoletoParcelas } from "@/components/boleto-parcelas";
import { getContractPaymentStatus } from "@/lib/pagamentos";
import { fetchLancamentos, createLancamento, parseValor, fmtBRL, type Lancamento } from "@/lib/financeiro-api";
import { CATEGORY_LABELS, CATEGORY_ORDER, getExclusiveConfig, getConflictsByItem, parseSelected, stringifySelected, type ExclusiveItem, type SelectedExclusive } from "@/lib/exclusive-items";
import { ArrowLeft, Save, Calendar, DollarSign, Package, FileText, ClipboardList, Image as ImageIcon, Upload, X, AlertTriangle, Lock, ShoppingCart, Hammer } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { supabase } from "@/integrations/supabase/client";
import logo from "@/assets/lhl-logo.png";

export const Route = createFileRoute("/admin/$id")({ component: ManageContract, head: () => ({ meta: [{ title: "Gerenciar Contrato — LHL Festas" }] }) });

const emptyDetails: ContractDetails = { dataEvento:"",dataRetirada:"",horaRetirada:"",dataDevolucao:"",horaDevolucao:"",nomeAniversariante:"",idadeAniversariante:"",tipoFesta:"",valorTotal:"",valorSinal:"",valorRestante:"",valorCaucao:"50",kit:{...emptyKit},balaoTipo:"",demaisPecas:"",observacoes:"",origemCliente:"",veioAnuncio:"Não",pagamentoFinalizado:"Não",devolucaoConfirmada:"Não",ativo:"Sim",observacoesInternas:"",sinalRecebido:"Não",pagamentoFinalRecebido:"Não",caucaoDevolvida:"Não",dataPagamentoFinal:"",dataDevolucaoCaucao:"",clienteRecorrente:"Não",aceiteContrato:"",dataHoraAceite:"",fotoDecoracaoUrl:"",checklistMontado:"Não",kitSeparado:"Não",caucaoRecebida:"Não",rua:"",numero:"",bairro:"",cidade:"",cep:"",itensExclusivos:"",itensComprar:"",itensProduzir:"",servicoMontagem:"Não" };
type ClientFields={nome:string;cpf:string;telefone:string;email:string;tema:string;modalidade:string;plano:string};
const emptyClient:ClientFields={nome:"",cpf:"",telefone:"",email:"",tema:"",modalidade:"",plano:""};

function ManageContract(){
 const {id}=Route.useParams(); const navigate=useNavigate();
 const [order,setOrder]=useState<StoredOrder|null>(null),[client,setClient]=useState<ClientFields>(emptyClient),[details,setDetails]=useState<ContractDetails>(emptyDetails),[initialDetails,setInitialDetails]=useState<ContractDetails>(emptyDetails),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false);
 type FluxoAsk={tipo:"sinal"|"final"|"caucaoRec"|"caucaoDev";valor:number}; const [askQueue,setAskQueue]=useState<FluxoAsk[]>([]); const askFluxo=askQueue[0]??null;
 const [existingLancIds,setExistingLancIds]=useState<Set<string>>(new Set()),[lancamentos,setLancamentos]=useState<Lancamento[]>([]),[allOrders,setAllOrders]=useState<StoredOrder[]>([]),[excCatalog,setExcCatalog]=useState<ExclusiveItem[]>([]);
 useEffect(()=>{setExcCatalog(getExclusiveConfig());try{seedCatalogo(getOrdensLocal().flatMap(o=>(o.compras||[]).map(c=>c.descricao)))}catch{}},[]);
 useEffect(()=>{const p=fetchOrdersFromSheet();p.then(setAllOrders).catch(()=>{});fetchLancamentos().then(ls=>{setLancamentos(ls);setExistingLancIds(new Set(ls.map(l=>`${l.contratoId}|${l.origem}`)))}).catch(()=>{});p.then(os=>os.find(x=>x.id===id)).then(o=>{if(!o)return;setOrder(o);const m={...emptyDetails,...(o.details??{})};if(!m.rua&&!m.bairro&&!m.cidade&&o.endereco)m.rua=o.endereco;if(!m.cidade&&o.cidadeUf)m.cidade=o.cidadeUf;setDetails(m);setInitialDetails(m);setClient({nome:o.nome??"",cpf:o.cpf??"",telefone:o.telefone??"",email:o.email??"",tema:o.tema??"",modalidade:o.modalidade??"",plano:o.plano??""})}).finally(()=>setLoaded(true))},[id]);
 const set=<K extends keyof ContractDetails>(k:K,v:ContractDetails[K])=>setDetails(d=>({...d,[k]:v})); const setC=<K extends keyof ClientFields>(k:K,v:ClientFields[K])=>setClient(c=>({...c,[k]:v}));
 const setKitQty=(k:keyof KitChecklist,q:number)=>setDetails(d=>({...d,kit:{...d.kit,[k]:Math.max(0,q)}})); const toggleKit=(k:keyof KitChecklist,ch:boolean)=>setDetails(d=>({...d,kit:{...d.kit,[k]:ch?(d.kit[k]||1):0}}));
 const enderecoCompleto=useMemo(()=>buildEnderecoCompleto(details),[details.rua,details.numero,details.bairro,details.cidade,details.cep]); const itensPendentesCount=countItensPendentes(details.observacoesInternas);
 const persist=async(wait=true)=>{if(!order)return false;setSaving(true);try{let ic=details.itensComprar,ip=details.itensProduzir;try{const f=await fetchOrderByIdPublic(order.id);if(f?.details){ic=stringifyItensComprar(mergePlanejamento(parseItensComprar(initialDetails.itensComprar),parseItensComprar(details.itensComprar),parseItensComprar(f.details.itensComprar)));ip=stringifyItensProduzir(mergePlanejamento(parseItensProduzir(initialDetails.itensProduzir),parseItensProduzir(details.itensProduzir),parseItensProduzir(f.details.itensProduzir)))}}catch{}
 await updateOrderOnSheet({id:order.id,createdAt:order.createdAt,status:order.status,nomeCompleto:client.nome,cpf:client.cpf,rg:"",telefone:client.telefone,email:client.email,endereco:enderecoCompleto,cidadeUf:details.cidade,tema:client.tema,modalidade:client.modalidade,plano:client.plano,dataEvento:details.dataEvento,dataRetirada:details.dataRetirada,horaRetirada:"",dataDevolucao:details.dataDevolucao,horaDevolucao:"",nomeAniversariante:details.nomeAniversariante,idadeAniversariante:details.idadeAniversariante,tipoFesta:details.tipoFesta,valorTotal:details.valorTotal,valorSinal:details.valorSinal,valorRestante:details.valorRestante,caucao:details.valorCaucao,demaisPecas:details.demaisPecas,observacoes:details.observacoes,kitJson:JSON.stringify(details.kit),veioAnuncio:details.veioAnuncio,observacoesInternas:details.observacoesInternas,sinalRecebido:details.sinalRecebido,pagamentoFinalRecebido:details.pagamentoFinalRecebido,caucaoDevolvida:details.caucaoDevolvida,dataPagamentoFinal:details.dataPagamentoFinal,dataDevolucaoCaucao:details.dataDevolucaoCaucao,aceiteContrato:details.aceiteContrato,dataHoraAceite:details.dataHoraAceite,fotoDecoracaoUrl:details.fotoDecoracaoUrl,checklistMontado:details.checklistMontado,kitSeparado:details.kitSeparado,caucaoRecebida:details.caucaoRecebida,rua:details.rua,numero:details.numero,bairro:details.bairro,cidade:details.cidade,cep:details.cep,balaoTipo:details.balaoTipo,servicoMontagem:details.servicoMontagem,itensExclusivos:details.itensExclusivos,itensComprar:ic,itensProduzir:ip});
 const df={...details,itensComprar:ic,itensProduzir:ip};const updated={...order,nome:client.nome,cpf:client.cpf,telefone:client.telefone,email:client.email,endereco:enderecoCompleto,cidadeUf:details.cidade,tema:client.tema,modalidade:client.modalidade,plano:client.plano,details:df};setDetails(df);setOrder(updated);
 const q:FluxoAsk[]=[];if(details.sinalRecebido==="Sim"&&initialDetails.sinalRecebido!=="Sim"&&!existingLancIds.has(`${order.id}|sinalRecebido`))q.push({tipo:"sinal",valor:parseValor(details.valorSinal)});if(details.pagamentoFinalRecebido==="Sim"&&initialDetails.pagamentoFinalRecebido!=="Sim"&&!existingLancIds.has(`${order.id}|pagamentoFinal`))q.push({tipo:"final",valor:Math.max(parseValor(details.valorTotal)-parseValor(details.valorSinal),0)});if(details.caucaoRecebida==="Sim"&&initialDetails.caucaoRecebida!=="Sim"&&!existingLancIds.has(`${order.id}|caucaoRecebida`))q.push({tipo:"caucaoRec",valor:parseValor(details.valorCaucao)});if(details.caucaoDevolvida==="Sim"&&initialDetails.caucaoDevolvida!=="Sim"&&!existingLancIds.has(`${order.id}|caucaoDevolvida`))q.push({tipo:"caucaoDev",valor:parseValor(details.valorCaucao)});if(q.length)setAskQueue(x=>[...x,...q]);setInitialDetails(df);
 const sync=async()=>{try{garantirMateriais([...parseItensComprar(ic).map(i=>i.nome),...parseItensProduzir(ip).map(i=>i.nome)]);const r=await sincronizarItensContrato(updated);if(r?.op&&r.enviarAprovacao.length){let op=r.op;for(const itemId of r.enviarAprovacao){const item=op.compras.find(c=>c.id===itemId);if(item&&compraStatusOf(item)==="Aguardando orçamento"){try{op=(await mudarEtapaCompra({op,itemId,status:"Aguardando autorização",order:updated})).op}catch{}}}}}catch{toast.error("Planejamento salvo, mas a sincronização operacional falhou. Salve novamente para tentar de novo.")}};const sp=sync();if(wait)await sp;else void sp;return true}catch{toast.error("Falha ao salvar na planilha.");return false}finally{setSaving(false)}};
 const askMeta=(a:FluxoAsk)=>a.tipo==="sinal"?{label:"Sinal",categoria:"Sinal",origem:"sinalRecebido",tipo:"Entrada" as const}:a.tipo==="final"?{label:"Pagamento Final",categoria:"Pagamento Final",origem:"pagamentoFinal",tipo:"Entrada" as const}:a.tipo==="caucaoRec"?{label:"Caução Recebida",categoria:"Caução Recebida",origem:"caucaoRecebida",tipo:"Entrada" as const}:{label:"Devolução de Caução",categoria:"Caução Devolvida",origem:"caucaoDevolvida",tipo:"Saída" as const};
 async function confirmarLancamento(){if(!askFluxo||!order)return;const m=askMeta(askFluxo);const l:Lancamento={id:crypto.randomUUID(),data:new Date().toISOString().slice(0,10),tipo:m.tipo,categoria:m.categoria,descricao:`${m.label} - ${client.nome||order.nome} - ${client.tema||order.tema||""}`.trim(),valor:askFluxo.valor,formaPagamento:"PIX",conta:"PIX",beneficiario:"",observacoes:"",contratoId:order.id,origem:m.origem,createdAt:new Date().toISOString(),ativo:"Sim"};try{await createLancamento(l);setExistingLancIds(p=>new Set(p).add(`${order.id}|${m.origem}`));setLancamentos(p=>[...p,l]);toast.success("Lançamento registrado no Fluxo de Caixa.")}catch{toast.error("Falha ao registrar no Fluxo de Caixa.")}finally{setAskQueue(p=>p.slice(1))}}
 const onSaveOnly=async(e:FormEvent)=>{e.preventDefault();if(await persist(false))toast.success("Alterações salvas com sucesso!")};const onGenerateContract=async()=>{if(order&&await persist())navigate({to:"/contract/$id",params:{id:order.id}})};const onGenerateChecklist=async()=>{if(order&&await persist())navigate({to:"/checklist/$id",params:{id:order.id}})};
 if(!loaded)return null;if(!order)return <div className="min-h-screen flex flex-col items-center justify-center gap-4"><p>Contrato não encontrado</p><Button asChild><Link to="/admin">Voltar</Link></Button></div>;
 const isMontagem=details.servicoMontagem==="Sim";
 return <div className="min-h-screen bg-background"><Toaster position="top-center" richColors/><header className="border-b bg-card/50"><div className="mx-auto max-w-4xl px-4 py-4 flex justify-between"><Link to="/admin" className="flex items-center gap-3"><img src={logo} alt="LHL Festas" className="w-12"/><span className="font-serif text-xl text-primary">LHL Festas</span></Link><Button asChild variant="ghost"><Link to="/admin"><ArrowLeft className="h-4 w-4 mr-2"/>Voltar</Link></Button></div></header><main className="mx-auto max-w-4xl px-4 py-8"><h1 className="font-serif text-4xl text-primary mb-2">Complementar Contrato</h1><p className="text-sm text-muted-foreground mb-8">Confira os dados e complete as informações da festa.</p><form onSubmit={onSaveOnly} className="space-y-8">
 <Section title="Dados do Contratante"><div className="grid sm:grid-cols-2 gap-4"><Field label="Nome Completo"><Input value={client.nome} onChange={e=>setC("nome",e.target.value)}/></Field><Field label="CPF"><Input value={client.cpf} onChange={e=>setC("cpf",e.target.value)}/></Field><Field label="Telefone"><Input value={client.telefone} onChange={e=>setC("telefone",e.target.value)}/></Field><Field label="E-mail"><Input value={client.email} onChange={e=>setC("email",e.target.value)}/></Field><Field label="Rua"><Input value={details.rua} onChange={e=>set("rua",e.target.value)}/></Field><Field label="Número"><Input value={details.numero} onChange={e=>set("numero",e.target.value)}/></Field><Field label="Bairro"><Input value={details.bairro} onChange={e=>set("bairro",e.target.value)}/></Field><Field label="Cidade"><Input value={details.cidade} onChange={e=>set("cidade",e.target.value)}/></Field><Field label="CEP"><Input value={details.cep} onChange={e=>set("cep",e.target.value)}/></Field></div></Section>
 <Section title="Dados da Festa" icon={<Package className="h-4 w-4"/>}><div className="grid sm:grid-cols-2 gap-4"><Field label="Tema"><Input value={client.tema} onChange={e=>setC("tema",e.target.value)}/></Field><Field label="Modalidade"><select className="h-10 rounded-md border px-3" value={client.modalidade} onChange={e=>{const v=e.target.value;setC("modalidade",v);setC("plano","");const mont=v==="Festa com Montagem";set("servicoMontagem",mont?"Sim":"Não");if(mont)set("valorCaucao","0")}}><option value="">—</option>{MODALIDADES.map(m=><option key={m.id} value={m.label}>{m.label}</option>)}</select></Field><Field label="Kit"><select className="h-10 rounded-md border px-3" value={client.plano} onChange={e=>setC("plano",e.target.value)}><option value="">—</option>{kitsForModalidadeLabel(client.modalidade).map(k=><option key={k.id} value={k.nome}>{k.nome}</option>)}</select></Field><Field label="Tipo da Festa"><Input value={details.tipoFesta} onChange={e=>set("tipoFesta",e.target.value)}/></Field><Field label="Nome do Aniversariante"><Input value={details.nomeAniversariante} onChange={e=>set("nomeAniversariante",e.target.value)}/></Field><Field label="Idade"><Input value={details.idadeAniversariante} onChange={e=>set("idadeAniversariante",e.target.value)}/></Field><Field label="Serviço de Montagem"><select className="h-10 rounded-md border px-3" value={details.servicoMontagem||"Não"} onChange={e=>{const v=e.target.value;set("servicoMontagem",v);if(v==="Sim")set("valorCaucao","0")}}><option value="Não">Não — retirada pelo cliente</option><option value="Sim">Sim — LHL monta/desmonta</option></select></Field></div>{isMontagem&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs text-emerald-700">Festa com montagem: caução isenta.</p>}</Section>
 <Section title="Datas do Evento" icon={<Calendar className="h-4 w-4"/>}><div className="grid sm:grid-cols-2 gap-4"><Field label="Data do Evento"><Input type="date" value={details.dataEvento} onChange={e=>set("dataEvento",e.target.value)}/></Field><Field label="Data de Retirada"><Input type="date" value={details.dataRetirada} onChange={e=>set("dataRetirada",e.target.value)}/></Field><Field label="Data de Devolução"><Input type="date" value={details.dataDevolucao} onChange={e=>set("dataDevolucao",e.target.value)}/></Field></div><p className="mt-3 text-xs text-muted-foreground">{HORARIO_AVISO}</p></Section>
 <Section title="Financeiro" icon={<DollarSign className="h-4 w-4"/>}><div className="grid sm:grid-cols-2 gap-4"><Field label="Valor Total Negociado (R$)"><Input value={details.valorTotal} onChange={e=>set("valorTotal",e.target.value)}/></Field><Field label="Valor do Sinal (R$)"><Input value={details.valorSinal} onChange={e=>set("valorSinal",e.target.value)}/></Field><Field label="Valor Restante (R$)"><Input value={details.valorRestante} onChange={e=>set("valorRestante",e.target.value)}/></Field><Field label="Caução (R$)"><Input value={details.valorCaucao} disabled={isMontagem} onChange={e=>set("valorCaucao",e.target.value)}/></Field></div><Button type="button" variant="outline" className="mt-4 rounded-full" onClick={()=>{const total=parseValor(details.valorTotal);if(total<=0){toast.error("Informe primeiro o valor total negociado.");return}const sinal=total/2;setDetails(d=>({...d,valorSinal:String(sinal),valorRestante:String(total-sinal),valorCaucao:d.servicoMontagem==="Sim"?"0":d.valorCaucao}));toast.success("Sinal e restante calculados em 50% sem alterar o valor negociado.")}}>Calcular 50% do valor negociado</Button><p className="mt-2 text-xs text-muted-foreground">O sistema nunca substitui o valor total negociado pelo preço de um kit.</p></Section>
 <Section title="Controle Administrativo" icon={<FileText className="h-4 w-4"/>}><div className="grid sm:grid-cols-2 gap-4">{([["Veio de anúncio?","veioAnuncio"],["Sinal Recebido?","sinalRecebido"],["Pagamento Final Recebido?","pagamentoFinalRecebido"],["Caução Recebida?","caucaoRecebida"],["Caução Devolvida?","caucaoDevolvida"],["Devolução Confirmada?","devolucaoConfirmada"]] as [string,keyof ContractDetails][]).map(([lab,k])=><Field key={String(k)} label={lab}><select className="h-10 rounded-md border px-3" value={String(details[k]||"Não")} onChange={e=>set(k,e.target.value as never)}><option>Não</option><option>Sim</option></select></Field>)}</div><p className="mt-3 text-xs text-muted-foreground">O evento sai das pendências operacionais quando a devolução/festa estiver finalizada ou quando a caução for devolvida. Em festa com montagem, a caução pode ser zero.</p>{(()=>{const p=getContractPaymentStatus({...order,details},lancamentos);return <div className="mt-5 grid sm:grid-cols-2 gap-3"><div className="rounded-xl border p-4">Recebido<br/><b>{fmtBRL(p.totalRecebido)}</b></div><div className="rounded-xl border p-4">Saldo pendente<br/><b>{fmtBRL(p.saldoReceber)}</b><p className="text-xs text-muted-foreground mt-1">Informativo para controle da equipe; não bloqueia tecnicamente entrega ou montagem.</p></div></div>})()}<BoletoParcelas contratoId={order.id} cliente={client.nome} saldoPendente={getContractPaymentStatus({...order,details},lancamentos).saldoReceber} dataEvento={details.dataEvento} onPagamentoRegistrado={()=>fetchLancamentos({force:true}).then(setLancamentos).catch(()=>{})}/><div className="mt-6"><Label>Itens Pendentes {itensPendentesCount?`(${itensPendentesCount})`:""}</Label><Textarea className="mt-2" value={details.observacoesInternas} onChange={e=>set("observacoesInternas",e.target.value)} rows={4}/></div></Section>
 <Section title="Checklist do Kit"><div className="grid sm:grid-cols-2 gap-3">{(Object.keys(kitLabels) as (keyof KitChecklist)[]).filter(k=>k!=="baloes").map(k=>{const q=details.kit[k]||0;return <div key={k} className="flex items-center gap-3 rounded-xl border p-3"><Checkbox checked={q>0} onCheckedChange={v=>toggleKit(k,v===true)}/><span className="flex-1 text-sm">{kitLabels[k]}</span><Input type="number" className="w-20" value={q||""} onChange={e=>setKitQty(k,Number(e.target.value)||0)}/></div>})}</div><div className="mt-5"><Label>Balões</Label><div className="grid sm:grid-cols-2 gap-2 mt-2">{BALAO_OPTIONS.map(opt=>{const list=(details.balaoTipo||"").split(", ").filter(Boolean),sel=list.includes(opt);return <label key={opt} className="flex gap-2"><Checkbox checked={sel} onCheckedChange={v=>set("balaoTipo",(v===true?[...list,opt]:list.filter(x=>x!==opt)).join(", "))}/>{opt}</label>})}</div></div><div className="mt-5"><Label>Demais peças</Label><Textarea value={details.demaisPecas} onChange={e=>set("demaisPecas",e.target.value)} rows={4}/></div></Section>
 <Section title="Itens a Comprar" icon={<ShoppingCart className="h-4 w-4"/>}><ItensComprarEditor itens={parseItensComprar(details.itensComprar)} onChange={l=>set("itensComprar",stringifyItensComprar(l))}/></Section><Section title="Itens a Produzir" icon={<Hammer className="h-4 w-4"/>}><ItensProduzirEditor itens={parseItensProduzir(details.itensProduzir)} onChange={l=>set("itensProduzir",stringifyItensProduzir(l))}/></Section>
 <Section title="Itens Exclusivos Reservados" icon={<Lock className="h-4 w-4"/>}><ExclusiveItemsSelector catalog={excCatalog} selected={parseSelected(details.itensExclusivos)} onChange={l=>set("itensExclusivos",stringifySelected(l))} allOrders={allOrders} currentContractId={order.id} dataEventoISO={details.dataEvento}/></Section>
 <Section title="Foto da Decoração Escolhida" icon={<ImageIcon className="h-4 w-4"/>}><PhotoDecoracao url={details.fotoDecoracaoUrl} onChange={u=>set("fotoDecoracaoUrl",u)} contratoId={order.id}/></Section><Section title="Observações"><Textarea value={details.observacoes} onChange={e=>set("observacoes",e.target.value)} rows={5}/></Section>
 <div className="flex flex-col sm:flex-row gap-3"><Button type="submit" disabled={saving}><Save className="h-4 w-4 mr-2"/>Salvar Alterações</Button><Button type="button" variant="outline" onClick={onGenerateContract}><FileText className="h-4 w-4 mr-2"/>Gerar Contrato</Button><Button type="button" variant="outline" onClick={onGenerateChecklist}><ClipboardList className="h-4 w-4 mr-2"/>Gerar Checklist</Button></div><p className="text-xs text-muted-foreground">A Ordem de Produção continua sendo criada e sincronizada automaticamente nos bastidores. A Josi não precisa abrir a Central de Produção para trabalhar neste contrato.</p>
 </form></main><AlertDialog open={!!askFluxo} onOpenChange={o=>!o&&setAskQueue(p=>p.slice(1))}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Registrar no Fluxo de Caixa?</AlertDialogTitle><AlertDialogDescription>{askFluxo?`Deseja registrar ${fmtBRL(askFluxo.valor)} no Fluxo de Caixa?`:""}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Agora não</AlertDialogCancel><AlertDialogAction onClick={confirmarLancamento}>Registrar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
}
function Section({title,icon,children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl bg-card border p-5 sm:p-7"><h2 className="font-serif text-xl text-primary flex gap-2 mb-5">{icon}{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label className="text-xs uppercase tracking-wider text-muted-foreground">{label}</Label>{children}</div>}
function ExclusiveItemsSelector({catalog,selected,onChange,allOrders,currentContractId,dataEventoISO}:{catalog:ExclusiveItem[];selected:SelectedExclusive[];onChange:(l:SelectedExclusive[])=>void;allOrders:StoredOrder[];currentContractId:string;dataEventoISO:string}){const conflicts=useMemo(()=>getConflictsByItem(allOrders,dataEventoISO,currentContractId),[allOrders,dataEventoISO,currentContractId]);if(!dataEventoISO)return <p className="text-sm text-muted-foreground">Preencha a data do evento para reservar itens exclusivos.</p>;const by:Record<string,ExclusiveItem[]>={};catalog.forEach(i=>(by[i.categoria]||=[]).push(i));return <div className="space-y-4">{CATEGORY_ORDER.filter(c=>by[c]?.length).map(c=><div key={c}><p className="text-xs font-bold mb-2">{CATEGORY_LABELS[c]}</p>{by[c].map(i=>{const sel=selected.some(s=>s.itemId===i.id),blocked=!sel&&(conflicts.get(i.id)?.length||0)>=i.quantidade&&!i.aComprar;return <label key={i.id} className="flex gap-3 border rounded-xl p-3"><Checkbox checked={sel} disabled={blocked} onCheckedChange={v=>onChange(v===true?[...selected.filter(s=>s.itemId!==i.id),{itemId:i.id}]:selected.filter(s=>s.itemId!==i.id))}/><span>{i.nome}{blocked?" — indisponível":""}</span></label>})}</div>)}</div>}
const ACCEPTED_MIME=["image/jpeg","image/jpg","image/png","image/webp"],MAX_UPLOAD_BYTES=5*1024*1024;
function PhotoDecoracao({url,onChange,contratoId}:{url:string;onChange:(u:string)=>void;contratoId:string}){const [uploading,setUploading]=useState(false),[preview,setPreview]=useState(false);async function handleFile(f:File){if(!f)return;if(!ACCEPTED_MIME.includes((f.type||"").toLowerCase())||f.size>MAX_UPLOAD_BYTES){toast.error("Imagem inválida ou maior que 5 MB.");return}setUploading(true);try{const ext=(f.name.split(".").pop()||"jpg").toLowerCase(),path=`${contratoId}/${Date.now()}.${ext}`;const {error}=await supabase.storage.from("contract-photos").upload(path,f,{upsert:true,contentType:f.type});if(error)throw error;const {data}=await supabase.storage.from("contract-photos").createSignedUrl(path,60*60*24*365*10);if(!data?.signedUrl)throw new Error();onChange(data.signedUrl)}catch{toast.error("Falha ao enviar foto.")}finally{setUploading(false)}}return <div>{url?<div className="flex gap-3"><button type="button" onClick={()=>setPreview(true)}><img src={url} className="w-40 h-40 object-contain rounded-xl border"/></button><Button type="button" variant="outline" onClick={()=>onChange("")}><X className="h-4 w-4"/>Remover</Button></div>:<label className="flex h-40 border-2 border-dashed rounded-xl items-center justify-center cursor-pointer"><Upload className="h-5 w-5 mr-2"/>{uploading?"Enviando...":"Enviar foto"}<input type="file" className="hidden" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&handleFile(e.target.files[0])}/></label>}<Dialog open={preview} onOpenChange={setPreview}><DialogContent>{url&&<img src={url} className="w-full max-h-[85vh] object-contain"/>}</DialogContent></Dialog></div>}
