import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useIsMobile } from "@/hooks/use-mobile";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { RefreshCw, Flame, ShoppingCart, Factory, Wallet, PackageCheck, ClipboardCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { StoredOrder } from "@/lib/orders-storage";
import { fetchOrdersFromSheet } from "@/lib/sheets-api";
import { setCachedSheetOrders } from "@/lib/orders-cache";
import { toDateISO, formatDateBR } from "@/lib/date-utils";
import { AdminShell } from "@/components/admin-shell";
import { MonthCalendar } from "@/components/MonthCalendar";
import { fetchLancamentos, fmtBRL, type Lancamento } from "@/lib/financeiro-api";
import { fetchPatrimonioFromSheet, type PatrimonioItem } from "@/lib/patrimonio-api";
import { fetchSolicitacoes } from "@/lib/solicitacoes-api";
import type { Solicitacao } from "@/lib/solicitacoes-types";
import { fetchOrdens, type ItemCompra, type OrdemProducao } from "@/lib/producao-api";
import { RegistrarCompraDialog } from "@/components/registrar-compra-dialog";
import { ConfirmarKitDialog, type ConfirmarKitAlvo } from "@/components/confirmar-kit-dialog";
import { buildDashboard, textoDias, URG_CLASS, URG_EMOJI, URG_LABEL, type LinkAlvo, type Ocorrencia, type Urgencia4, type DashboardData } from "@/lib/dashboard-aggregator";

export const Route = createFileRoute("/admin/")({ component: CentralPage });
function AlvoLink({link,children,className}:{link:LinkAlvo;children:React.ReactNode;className?:string}){return <Link {...(link as any)} className={className}>{children}</Link>}
function UrgBadge({nivel}:{nivel:Urgencia4}){return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] ${URG_CLASS[nivel]}`}>{URG_EMOJI[nivel]} {URG_LABEL[nivel]}</span>}

function CentralPage(){
 const isMobile=useIsMobile();const [orders,setOrders]=useState<StoredOrder[]>([]),[lancamentos,setLancamentos]=useState<Lancamento[]>([]),[patrimonio,setPatrimonio]=useState<PatrimonioItem[]>([]),[ordens,setOrdens]=useState<OrdemProducao[]>([]),[solicitacoes,setSolicitacoes]=useState<Solicitacao[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);const [monthCursor,setMonthCursor]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)});const navigate=useNavigate();const [compraAlvo,setCompraAlvo]=useState<{op:OrdemProducao;item:ItemCompra;cliente:string}|null>(null);const loadingRef=useRef(false);
 const load=useCallback(async(showToast=false)=>{if(loadingRef.current)return;loadingRef.current=true;setRefreshing(true);try{const [remote,lanc,pat,ops,sols]=await Promise.all([fetchOrdersFromSheet().catch(()=>[] as StoredOrder[]),fetchLancamentos().catch(()=>[] as Lancamento[]),fetchPatrimonioFromSheet().catch(()=>[] as PatrimonioItem[]),fetchOrdens().catch(()=>[] as OrdemProducao[]),fetchSolicitacoes().catch(()=>[] as Solicitacao[])]);const safeOrders=Array.isArray(remote)?remote:[];setOrders(safeOrders);setLancamentos(Array.isArray(lanc)?lanc:[]);setPatrimonio(Array.isArray(pat)?pat:[]);setOrdens(Array.isArray(ops)?ops:[]);setSolicitacoes(Array.isArray(sols)?sols:[]);setCachedSheetOrders(safeOrders);if(showToast)toast.success("Dados atualizados.")}catch(e){console.error(e);toast.error("Não foi possível carregar todos os dados.")}finally{setLoading(false);setRefreshing(false);loadingRef.current=false}},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const t=setInterval(()=>void load(),90000),f=()=>void load();window.addEventListener("focus",f);return()=>{clearInterval(t);window.removeEventListener("focus",f)}},[load]);
 const dash=useMemo(()=>buildDashboard({orders,ops:ordens,solicitacoes,lancamentos,filtro:{periodo:"todos",urgencia:"todas",responsavel:"",modalidade:"",kit:""}}),[orders,ordens,solicitacoes,lancamentos]);
 const today=new Date(),todayISO=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`,in7=new Date(today.getTime()+7*86400000),in7ISO=`${in7.getFullYear()}-${String(in7.getMonth()+1).padStart(2,"0")}-${String(in7.getDate()).padStart(2,"0")}`;const events=useMemo(()=>{const m=new Map<string,StoredOrder[]>();orders.forEach(o=>{if(o.status==="Cancelado")return;const iso=toDateISO(o.details?.dataEvento);if(!iso)return;m.set(iso,[...(m.get(iso)||[]),o])});return m},[orders]);
 return <AdminShell><RegistrarCompraDialog open={!!compraAlvo} op={compraAlvo?.op} item={compraAlvo?.item} cliente={compraAlvo?.cliente} solicitacao={solicitacoes.find(s=>s.origemItemId===compraAlvo?.item.id)} onOpenChange={o=>!o&&setCompraAlvo(null)} onSuccess={op=>{setOrdens(p=>p.map(x=>x.id===op.id?op:x));void load(true)}}/><main className="mx-auto max-w-6xl space-y-6 px-4 py-6"><header className="flex items-end justify-between"><div><h1 className="font-serif text-3xl text-primary">Painel da Josi</h1><p className="text-sm text-muted-foreground">{loading?"Sincronizando operação...":"Seu resumo operacional simplificado."}</p></div><Button variant="outline" onClick={()=>load(true)} disabled={refreshing}><RefreshCw className={`mr-2 h-4 w-4 ${refreshing?"animate-spin":""}`}/>Atualizar</Button></header><MonthCalendar cursor={monthCursor} onPrev={()=>setMonthCursor(new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1))} onNext={()=>setMonthCursor(new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1))} onToday={()=>setMonthCursor(new Date(today.getFullYear(),today.getMonth(),1))} eventsByDay={events} onOpen={id=>navigate({to:"/admin/$id",params:{id}})} todayISO={todayISO} in7ISO={in7ISO} ordens={ordens}/>{dash.facaPrimeiro&&<section className="rounded-2xl border border-red-500/40 bg-red-500/5 p-5"><div className="flex items-center gap-3"><Flame className="h-5 w-5 text-red-600"/><div className="flex-1"><b>{dash.facaPrimeiro.titulo}</b><p className="text-sm">{dash.facaPrimeiro.descricao}</p></div><Button asChild><AlvoLink link={dash.facaPrimeiro.link}>{dash.facaPrimeiro.acaoLabel}</AlvoLink></Button></div></section>}{dash.confirmacoesKit?.length>0&&!isMobile&&<ConfirmarKitBloco dash={dash} ordens={ordens} onAtualizado={op=>setOrdens(p=>p.map(x=>x.id===op.id?op:x))}/>}<div className="grid gap-6 md:grid-cols-2"><SectionBloco titulo="Próximas Tarefas" icone={<ClipboardCheck className="h-5 w-5"/>} itens={dash.tarefas} vazio="Nenhuma tarefa crítica pendente."/><SectionBloco titulo="Compras Autorizadas" icone={<ShoppingCart className="h-5 w-5"/>} itens={dash.comprasPend} vazio="Tudo comprado!" onRegistrarCompra={o=>{const op=ordens.find(x=>x.id===o.opId),item=op?.compras.find(x=>x.id===o.itemId);if(op&&item)setCompraAlvo({op,item,cliente:o.cliente})}}/><SectionBloco titulo="Produções Pendentes" icone={<Factory className="h-5 w-5"/>} itens={dash.producoesPend} vazio="Produção em dia."/></div><section className="rounded-2xl border bg-card p-5"><h2 className="mb-4 flex gap-2"><Wallet className="h-4 w-4"/>Financeiro</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Mini label="Entradas" valor={fmtBRL(dash.financeiro.entradasSemana)}/><Mini label="Saídas" valor={fmtBRL(dash.financeiro.saidasSemana)}/><Mini label="A receber" valor={fmtBRL(dash.ordens.reduce((s,o)=>s+o.saldoReceber,0))}/><Mini label="Saldo atual" valor={fmtBRL(dash.financeiro.saldoAtual)}/></div></section></main></AdminShell>}
function SectionBloco({titulo,icone,itens,vazio,onRegistrarCompra}:{titulo:string;icone:React.ReactNode;itens:Ocorrencia[];vazio:string;onRegistrarCompra?:(o:Ocorrencia)=>void}){return <section className="space-y-4 rounded-2xl border bg-card p-5"><div className="flex gap-2 border-b pb-3">{icone}<h2>{titulo}</h2><Badge className="ml-auto">{itens.length}</Badge></div>{!itens.length?<p className="text-sm text-muted-foreground">{vazio}</p>:itens.slice(0,15).map(o=><div key={o.id} className="rounded-xl border p-3"><div className="flex gap-2"><UrgBadge nivel={o.urgencia}/><b className="truncate text-sm">{o.cliente}</b></div><p className="mt-1 text-xs">{o.titulo} · {o.dataLimite?formatDateBR(o.dataLimite):"—"}</p>{o.acaoLabel==="Registrar compra"?<Button size="sm" className="mt-2" onClick={()=>onRegistrarCompra?.(o)}>Registrar compra</Button>:<Button asChild size="sm" variant="outline" className="mt-2"><AlvoLink link={o.link}>{o.acaoLabel}</AlvoLink></Button>}</div>)}</section>}
function Mini({label,valor}:{label:string;valor:number|string}){return <div className="rounded-xl border p-3"><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className="font-serif text-lg text-primary">{valor}</p></div>}
function ConfirmarKitBloco({dash,ordens,onAtualizado}:{dash:DashboardData;ordens:OrdemProducao[];onAtualizado:(op:OrdemProducao)=>void}){const [alvo,setAlvo]=useState<ConfirmarKitAlvo|null>(null);return <section className="rounded-2xl border border-emerald-500/40 bg-emerald-500/5 p-5"><h2 className="flex gap-2 text-emerald-700"><PackageCheck className="h-4 w-4"/>Confirmar Kit Pronto?</h2>{dash.confirmacoesKit.map(o=><div key={o.opId} className="mt-2 flex items-center justify-between rounded-xl border bg-card p-3"><span>{o.cliente} · {o.numero}</span><Button size="sm" onClick={()=>{const op=ordens.find(x=>x.id===o.opId);if(op)setAlvo({op,cliente:o.cliente,origem:"Dashboard"})}}>Confirmar</Button></div>)}<ConfirmarKitDialog alvo={alvo} onClose={()=>setAlvo(null)} onAtualizado={op=>{onAtualizado(op);setAlvo(null)}}/></section>}
