import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { RefreshCw, Flame, ShoppingCart, Factory, Wallet, ClipboardCheck, AlertTriangle, Trash2, MessageCircle, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { StoredOrder } from "@/lib/orders-storage";
import { WHATSAPP_NUMBER } from "@/lib/orders-storage";
import { fetchOrdersFromSheet, setOrderStatusOnSheet } from "@/lib/sheets-api";
import { setCachedSheetOrders } from "@/lib/orders-cache";
import { toDateISO, formatDateBR } from "@/lib/date-utils";
import { AdminShell } from "@/components/admin-shell";
import { MonthCalendar } from "@/components/MonthCalendar";
import { fetchLancamentos, fmtBRL, type Lancamento } from "@/lib/financeiro-api";
import { fetchPatrimonioFromSheet, type PatrimonioItem } from "@/lib/patrimonio-api";
import { fetchSolicitacoes } from "@/lib/solicitacoes-api";
import type { Solicitacao } from "@/lib/solicitacoes-types";
import { fetchOrdens, updateItemProducaoStatus, type ItemCompra, type OrdemProducao } from "@/lib/producao-api";
import { RegistrarCompraDialog } from "@/components/registrar-compra-dialog";
import { buildDashboard, URG_CLASS, URG_EMOJI, URG_LABEL, type LinkAlvo, type Ocorrencia, type Urgencia4 } from "@/lib/dashboard-aggregator";
import { getContractPaymentStatus, indexRecebimentos } from "@/lib/pagamentos";
import { contratoOperacionalmenteAtivo, idsContratosOperacionaisAtivos } from "@/lib/contrato-operacional";
import { fetchLeadsFromSheet, updateLeadStatusOnSheet, type LeadRecord } from "@/lib/leads-api";

export const Route = createFileRoute("/admin/")({ component: CentralPage });
function AlvoLink({link,children,className}:{link:LinkAlvo;children:React.ReactNode;className?:string}){return <Link {...(link as any)} className={className}>{children}</Link>}
function UrgBadge({nivel}:{nivel:Urgencia4}){return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] ${URG_CLASS[nivel]}`}>{URG_EMOJI[nivel]} {URG_LABEL[nivel]}</span>}
function normalizeWa(v:string){let d=String(v||"").replace(/\D/g,"");if(d.startsWith("55")&&(d.length===12||d.length===13))d=d.slice(2);return d}
function waUrl(lead:LeadRecord){const d=normalizeWa(lead.whatsappNormalizado||lead.whatsapp);const n=d.length===10||d.length===11?`55${d}`:(d||WHATSAPP_NUMBER);const primeiro=(lead.nome||"").trim().split(" ")[0]||"";const msg=`Olá, ${primeiro}!\n\nAqui é da LHL Festas. Recebemos sua solicitação de orçamento e vou dar continuidade ao seu atendimento por aqui. 😊`;return `https://wa.me/${n}?text=${encodeURIComponent(msg)}`}
function comTimeout<T>(promise:Promise<T>, fallback:T, ms=7000):Promise<T>{return Promise.race([promise.catch(()=>fallback),new Promise<T>(resolve=>setTimeout(()=>resolve(fallback),ms))])}

function CentralPage(){
 const [orders,setOrders]=useState<StoredOrder[]>([]),[lancamentos,setLancamentos]=useState<Lancamento[]>([]),[patrimonio,setPatrimonio]=useState<PatrimonioItem[]>([]),[ordens,setOrdens]=useState<OrdemProducao[]>([]),[solicitacoes,setSolicitacoes]=useState<Solicitacao[]>([]),[leads,setLeads]=useState<LeadRecord[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);const [monthCursor,setMonthCursor]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)});const navigate=useNavigate();const [compraAlvo,setCompraAlvo]=useState<{op:OrdemProducao;item:ItemCompra;cliente:string}|null>(null);const [excluindo,setExcluindo]=useState<string|null>(null);const [contatandoLead,setContatandoLead]=useState<string|null>(null);const loadingRef=useRef(false);
 const load=useCallback(async(showToast=false)=>{if(loadingRef.current)return;loadingRef.current=true;setRefreshing(true);let contratosOk=false;try{const remote=await comTimeout(fetchOrdersFromSheet(),[] as StoredOrder[],7000);const safeOrders=Array.isArray(remote)?remote:[];setOrders(safeOrders);setCachedSheetOrders(safeOrders);contratosOk=safeOrders.length>0;if(!contratosOk&&showToast)toast.warning("Não foi possível atualizar os contratos agora.")}catch(e){console.error(e);if(showToast)toast.error("Não foi possível atualizar contratos e agenda.")}finally{setLoading(false)}
 void Promise.allSettled([
  comTimeout(fetchLancamentos(),[] as Lancamento[]).then(v=>setLancamentos(Array.isArray(v)?v:[])),
  comTimeout(fetchPatrimonioFromSheet(),[] as PatrimonioItem[]).then(v=>setPatrimonio(Array.isArray(v)?v:[])),
  comTimeout(fetchOrdens(),[] as OrdemProducao[]).then(v=>setOrdens(Array.isArray(v)?v:[])),
  comTimeout(fetchSolicitacoes(),[] as Solicitacao[]).then(v=>setSolicitacoes(Array.isArray(v)?v:[])),
  comTimeout(fetchLeadsFromSheet(),[] as LeadRecord[]).then(v=>setLeads(Array.isArray(v)?v:[])),
 ]).finally(()=>{setRefreshing(false);loadingRef.current=false;if(showToast&&contratosOk)toast.success("Dados atualizados.")})},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const t=setInterval(()=>void load(),90000),f=()=>void load();window.addEventListener("focus",f);return()=>{clearInterval(t);window.removeEventListener("focus",f)}},[load]);
 const today=new Date(),todayISO=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`,in7=new Date(today.getTime()+7*86400000),in7ISO=`${in7.getFullYear()}-${String(in7.getMonth()+1).padStart(2,"0")}-${String(in7.getDate()).padStart(2,"0")}`;
 const novosLeads=useMemo(()=>leads.filter(l=>l.status==="Novo Lead").sort((a,b)=>(b.createdAt||"").localeCompare(a.createdAt||"")),[leads]);
 const activeOrders=useMemo(()=>orders.filter(o=>contratoOperacionalmenteAtivo(o,todayISO)),[orders,todayISO]);
 const activeIds=useMemo(()=>idsContratosOperacionaisAtivos(orders,todayISO),[orders,todayISO]);
 const activeOrdens=useMemo(()=>ordens.filter(op=>activeIds.has(String(op.contratoId))&&op.status!=="Finalizado"),[ordens,activeIds]);
 const activeSolicitacoes=useMemo(()=>solicitacoes.filter(s=>{const pedidoId=String((s as any).pedidoId||"");return !pedidoId||activeIds.has(pedidoId)}),[solicitacoes,activeIds]);
 const dash=useMemo(()=>buildDashboard({orders:activeOrders,ops:activeOrdens,solicitacoes:activeSolicitacoes,lancamentos,filtro:{periodo:"todos",urgencia:"todas",responsavel:"",modalidade:"",kit:""}}),[activeOrders,activeOrdens,activeSolicitacoes,lancamentos]);
 const events=useMemo(()=>{const m=new Map<string,StoredOrder[]>();activeOrders.forEach(o=>{const iso=toDateISO(o.details?.dataEvento);if(!iso)return;m.set(iso,[...(m.get(iso)||[]),o])});return m},[activeOrders]);
 const alertasSinal=useMemo(()=>{const idx=indexRecebimentos(lancamentos);const hoje=new Date(`${todayISO}T12:00:00`);return activeOrders.map(o=>{const iso=toDateISO(o.details?.dataEvento);if(!iso)return null;const evt=new Date(`${iso}T12:00:00`);const dias=Math.ceil((evt.getTime()-hoje.getTime())/86400000);const pag=getContractPaymentStatus(o,idx);if(dias<0||dias>15||pag.totalRecebido>0)return null;return {o,dias,iso};}).filter(Boolean).sort((a:any,b:any)=>a.dias-b.dias) as {o:StoredOrder;dias:number;iso:string}[]},[activeOrders,lancamentos,todayISO]);
 async function excluirContrato(o:StoredOrder){if(!window.confirm(`Excluir o pré-contrato de ${o.nome}? Ele sairá das filas ativas, mas o histórico será preservado.`))return;setExcluindo(o.id);try{await setOrderStatusOnSheet(o.id,"Excluído");toast.success("Pré-contrato excluído.");await load()}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível excluir o pré-contrato.")}finally{setExcluindo(null)}}
 async function chamarLead(lead:LeadRecord){window.open(waUrl(lead),"_blank","noopener,noreferrer");setContatandoLead(lead.id);try{await updateLeadStatusOnSheet(lead.id,"Em Atendimento");setLeads(p=>p.map(l=>l.id===lead.id?{...l,status:"Em Atendimento"}:l));toast.success("Lead movido para Em Atendimento.")}catch(e){console.error(e);toast.warning("WhatsApp aberto, mas não foi possível atualizar o status do lead.")}finally{setContatandoLead(null)}}
 return <AdminShell><RegistrarCompraDialog open={!!compraAlvo} op={compraAlvo?.op} item={compraAlvo?.item} cliente={compraAlvo?.cliente} solicitacao={activeSolicitacoes.find(s=>s.origemItemId===compraAlvo?.item.id)} onOpenChange={o=>!o&&setCompraAlvo(null)} onSuccess={op=>{setOrdens(p=>p.map(x=>x.id===op.id?op:x));void load(true)}}/><main className="mx-auto max-w-6xl space-y-6 px-4 py-6"><header className="flex items-end justify-between"><div><h1 className="font-serif text-3xl text-primary">Painel da Josi</h1><p className="text-sm text-muted-foreground">{loading?"Carregando contratos e agenda...":refreshing?"Atualizando módulos auxiliares...":"Seu resumo operacional simplificado."}</p></div><Button variant="outline" onClick={()=>load(true)} disabled={refreshing}><RefreshCw className={`mr-2 h-4 w-4 ${refreshing?"animate-spin":""}`}/>Atualizar</Button></header>
 {novosLeads.length>0&&<section className="rounded-2xl border border-sky-500/40 bg-sky-500/5 p-5"><div className="mb-3 flex items-center gap-2"><Users className="h-5 w-5 text-sky-700"/><div><h2 className="font-semibold text-sky-900">Novos Leads — responder agora</h2><p className="text-xs text-sky-800/80">Novos pedidos de orçamento aguardando primeiro atendimento.</p></div><Badge className="ml-auto bg-sky-600">{novosLeads.length}</Badge></div><div className="space-y-2">{novosLeads.slice(0,10).map(l=><div key={l.id} className="flex flex-col gap-3 rounded-xl border bg-card p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{l.nome||"Lead sem nome"}</p><p className="text-xs text-muted-foreground">{l.tema||"Tema não informado"}{l.dataFesta?` · Festa ${formatDateBR(toDateISO(l.dataFesta))}`:""}{l.origem?` · ${l.origem}`:""}</p><p className="mt-1 text-xs font-semibold text-sky-800">Novo lead aguardando atendimento</p></div><div className="flex gap-2"><Button size="sm" onClick={()=>void chamarLead(l)} disabled={contatandoLead===l.id}><MessageCircle className="mr-1 h-4 w-4"/>{contatandoLead===l.id?"Abrindo...":"Chamar no WhatsApp"}</Button><Button asChild size="sm" variant="outline"><Link to="/admin/leads">Ver detalhes</Link></Button></div></div>)}</div>{novosLeads.length>10&&<p className="mt-3 text-xs text-sky-800">Há mais {novosLeads.length-10} lead(s) novo(s). Abra Novos Leads para ver todos.</p>}</section>}
 {alertasSinal.length>0&&<section className="rounded-2xl border border-amber-500/45 bg-amber-500/5 p-5"><div className="mb-3 flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-700"/><div><h2 className="font-semibold text-amber-900">Pré-contratos sem sinal — atenção</h2><p className="text-xs text-amber-800/80">Festas a 15 dias ou menos sem nenhum recebimento confirmado.</p></div><Badge className="ml-auto bg-amber-600">{alertasSinal.length}</Badge></div><div className="space-y-2">{alertasSinal.map(({o,dias,iso})=><div key={o.id} className="flex flex-col gap-3 rounded-xl border bg-card p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{o.nome}</p><p className="text-xs text-muted-foreground">{o.tema||"Sem tema"} · Festa {formatDateBR(iso)} · {dias===0?"hoje":dias===1?"em 1 dia":`em ${dias} dias`}</p><p className="mt-1 text-xs font-semibold text-amber-800">Sinal ainda não recebido</p></div><div className="flex gap-2"><Button asChild size="sm" variant="outline"><Link to="/admin/$id" params={{id:o.id}}>Abrir contrato</Link></Button><Button size="sm" variant="destructive" disabled={excluindo===o.id} onClick={()=>void excluirContrato(o)}><Trash2 className="mr-1 h-4 w-4"/>{excluindo===o.id?"Excluindo...":"Excluir contrato"}</Button></div></div>)}</div></section>}
 <MonthCalendar cursor={monthCursor} onPrev={()=>setMonthCursor(new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1))} onNext={()=>setMonthCursor(new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1))} onToday={()=>setMonthCursor(new Date(today.getFullYear(),today.getMonth(),1))} eventsByDay={events} onOpen={id=>navigate({to:"/admin/$id",params:{id}})} todayISO={todayISO} in7ISO={in7ISO} ordens={activeOrdens}/>{dash.facaPrimeiro&&<section className="rounded-2xl border border-red-500/40 bg-red-500/5 p-5"><div className="flex items-center gap-3"><Flame className="h-5 w-5 text-red-600"/><div className="flex-1"><b>{dash.facaPrimeiro.titulo}</b><p className="text-sm">{dash.facaPrimeiro.descricao}</p></div><Button asChild><AlvoLink link={dash.facaPrimeiro.link}>{dash.facaPrimeiro.acaoLabel}</AlvoLink></Button></div></section>}
 <div className="grid gap-6 md:grid-cols-2"><SectionBloco titulo="Próximas Tarefas" icone={<ClipboardCheck className="h-5 w-5"/>} itens={dash.tarefas} vazio="Nenhuma tarefa crítica pendente."/><SectionBloco titulo="Compras Autorizadas" icone={<ShoppingCart className="h-5 w-5"/>} itens={dash.comprasPend} vazio="Tudo comprado!" onRegistrarCompra={o=>{const op=activeOrdens.find(x=>x.id===o.opId),item=op?.compras.find(x=>x.id===o.itemId);if(op&&item)setCompraAlvo({op,item,cliente:o.cliente})}}/><SectionBloco titulo="Produções Pendentes" icone={<Factory className="h-5 w-5"/>} itens={dash.producoesPend} vazio="Produção em dia." onMarcarProduzido={async o=>{if(!o.opId||!o.itemId)return;try{const op=await updateItemProducaoStatus(o.opId,o.itemId,"Concluído");setOrdens(p=>p.some(x=>x.id===op.id)?p.map(x=>x.id===op.id?op:x):[op,...p]);toast.success("Item marcado como produzido!")}catch(e){toast.error(e instanceof Error?e.message:"Erro ao atualizar produção.")}}}/></div>
 <section className="rounded-2xl border bg-card p-5"><h2 className="mb-4 flex gap-2"><Wallet className="h-4 w-4"/>Financeiro</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Mini label="Entradas últimos 7 dias" valor={fmtBRL(dash.financeiro.entradasSemana)}/><Mini label="Saídas últimos 7 dias" valor={fmtBRL(dash.financeiro.saidasSemana)}/><Mini label="A receber" valor={fmtBRL(dash.ordens.reduce((s,o)=>s+o.saldoReceber,0))}/><Mini label="Saldo atual" valor={fmtBRL(dash.financeiro.saldoAtual)}/></div></section></main></AdminShell>}
function SectionBloco({titulo,icone,itens,vazio,onRegistrarCompra,onMarcarProduzido}:{titulo:string;icone:React.ReactNode;itens:Ocorrencia[];vazio:string;onRegistrarCompra?:(o:Ocorrencia)=>void;onMarcarProduzido?:(o:Ocorrencia)=>void|Promise<void>}){return <section className="space-y-4 rounded-2xl border bg-card p-5"><div className="flex gap-2 border-b pb-3">{icone}<h2>{titulo}</h2><Badge className="ml-auto">{itens.length}</Badge></div>{!itens.length?<p className="text-sm text-muted-foreground">{vazio}</p>:itens.slice(0,15).map(o=><div key={o.id} className="rounded-xl border p-3"><div className="flex gap-2"><UrgBadge nivel={o.urgencia}/><b className="truncate text-sm">{o.cliente}</b></div><p className="mt-1 text-xs">{o.titulo} · {o.dataLimite?formatDateBR(o.dataLimite):"—"}</p>{o.acaoLabel==="Registrar compra"?<Button size="sm" className="mt-2" onClick={()=>onRegistrarCompra?.(o)}>Registrar compra</Button>:o.acaoLabel==="Marcar como produzido"?<Button size="sm" className="mt-2" onClick={()=>void onMarcarProduzido?.(o)}>Marcar Produzido</Button>:<Button asChild size="sm" variant="outline" className="mt-2"><AlvoLink link={o.link}>{o.acaoLabel}</AlvoLink></Button>}</div>)}</section>}
function Mini({label,valor}:{label:string;valor:number|string}){return <div className="rounded-xl border p-3"><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className="font-serif text-lg text-primary">{valor}</p></div>}
