import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { kitLabels, type StoredOrder, type KitChecklist } from "@/lib/orders-storage";
import { fetchOrdersFromSheet } from "@/lib/sheets-api";
import { fetchLancamentos, type Lancamento } from "@/lib/financeiro-api";
import { getContractPaymentStatus, indexRecebimentos } from "@/lib/pagamentos";
import { formatDateBR, formatDateTimeBR } from "@/lib/date-utils";
import { kitItemsFor } from "@/data/kits";
import { matchStructureModel, type StructureModel } from "@/lib/structure-models";
import { CATEGORY_LABELS, getExclusiveConfig, parseSelected, type ExclusiveItem } from "@/lib/exclusive-items";
import { ArrowLeft, Printer, Download, Loader2 } from "lucide-react";
import logo from "@/assets/lhl-logo.png";
import { downloadElementPdf, printElement } from "@/lib/print-doc";

export const Route = createFileRoute("/checklist/$id")({ component: ChecklistPrint, head: () => ({ meta: [{ title: "Checklist Operacional — LHL Festas" }] }) });

type GroupKey = "ESTRUTURAS" | "MOBILIÁRIO" | "DECORAÇÃO" | "ITENS DO TEMA" | "EXTRAS" | "OUTROS ITENS";
const KIT_GROUP: Record<keyof KitChecklist, GroupKey> = { painelPersonalizado:"ESTRUTURAS",arcoSuporte:"ESTRUTURAS",mesa:"MOBILIÁRIO",cilindros:"MOBILIÁRIO",bandejas:"DECORAÇÃO",boloFake:"DECORAÇÃO",vasoGrego:"DECORAÇÃO",buchinhoFloreira:"DECORAÇÃO",tapete:"DECORAÇÃO",displays:"ITENS DO TEMA",baloes:"EXTRAS",numeroLed:"EXTRAS",escadinha:"MOBILIÁRIO",happyBirthday:"EXTRAS" };
const GROUP_ORDER: GroupKey[] = ["ESTRUTURAS","MOBILIÁRIO","DECORAÇÃO","ITENS DO TEMA","EXTRAS","OUTROS ITENS"];
function classifyExtra(label:string):GroupKey{const t=label.toLowerCase();if(/painel|arco|estrutura/.test(t))return"ESTRUTURAS";if(/mesa|cilindro|escadinh/.test(t))return"MOBILIÁRIO";if(/bandeja|boleir|mini ?cake|vaso|buchinh|floreir|bolo fake|tapete/.test(t))return"DECORAÇÃO";if(/display|tema|personaliz/.test(t))return"ITENS DO TEMA";if(/led|lumin|happy|balão|balao|número|numero/.test(t))return"EXTRAS";return"OUTROS ITENS"}

function ChecklistPrint(){
 const {id}=Route.useParams();const [order,setOrder]=useState<StoredOrder|null>(null),[loaded,setLoaded]=useState(false),[lancamentos,setLancamentos]=useState<Lancamento[]>([]),[busy,setBusy]=useState<"pdf"|"print"|null>(null);
 useEffect(()=>{void Promise.all([fetchLancamentos().catch(()=>[] as Lancamento[]),fetchOrdersFromSheet({includeDeleted:true,force:true})]).then(([l,orders])=>{setLancamentos(l);const o=orders.find(x=>x.id===id);if(o&&String(o.status)!=="Excluído")setOrder(o)}).finally(()=>setLoaded(true))},[id]);
 if(!loaded)return null;if(!order)return <div className="flex min-h-screen flex-col items-center justify-center gap-4"><p className="font-serif text-2xl text-primary">Contrato não encontrado</p><Button asChild variant="ghost"><Link to="/admin"><ArrowLeft className="mr-2 h-4 w-4"/>Voltar</Link></Button></div>;
 const d=order.details;const isMontagem=d?.servicoMontagem==="Sim";const pagamento=getContractPaymentStatus(order,indexRecebimentos(lancamentos));const fmt=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
 const kitItems=(Object.keys(kitLabels) as (keyof KitChecklist)[]).map(k=>({label:kitLabels[k],qty:Number(d?.kit?.[k])||0,group:KIT_GROUP[k]})).filter(x=>x.qty>0);
 const rawExtras:{label:string;qty:number}[]=[];for(const raw of String(d?.demaisPecas||"").split(/\r?\n|;/)){const line=raw.trim();if(!line)continue;const m=line.match(/^(.+?)\s*[:\-]\s*(\d+)/);rawExtras.push(m?{label:m[1].trim(),qty:Number(m[2])}:{label:line,qty:1})}
 const structures:{model:StructureModel;qty:number;sourceLabel:string}[]=[];const extraItems:{label:string;qty:number;group:GroupKey}[]=[];for(const it of rawExtras){const model=matchStructureModel(it.label);if(model)structures.push({model,qty:it.qty,sourceLabel:it.label});else extraItems.push({...it,group:classifyExtra(it.label)})}
 const grouped:Record<GroupKey,{label:string;qty:number}[]>={"ESTRUTURAS":[],"MOBILIÁRIO":[],"DECORAÇÃO":[],"ITENS DO TEMA":[],"EXTRAS":[],"OUTROS ITENS":[]};for(const it of [...kitItems,...extraItems])grouped[it.group].push({label:it.label,qty:it.qty});if(d?.balaoTipo?.trim())grouped.EXTRAS.push({label:`Balões — ${d.balaoTipo.trim()}`,qty:1});
 const excCatalog:ExclusiveItem[]=getExclusiveConfig();const excMap=new Map(excCatalog.map(i=>[i.id,i]));const excItems=parseSelected(d?.itensExclusivos).flatMap(s=>{const c=excMap.get(s.itemId);return c?[{...c,aComprarSpec:s.aComprarSpec}]:[]});const kitItensChecklist=kitItemsFor(order.modalidade,order.plano);
 const blank=<span className="inline-block min-w-[70px] border-b border-black">&nbsp;</span>;const sanitize=(s:string)=>s.replace(/[\\/:*?"<>|]+/g,"").trim();const filename=`Checklist LHL - ${sanitize(order.nome||"Cliente")}.pdf`;const el=()=>document.querySelector(".a4-checklist") as HTMLElement|null;
 async function pdf(){const x=el();if(!x)return;setBusy("pdf");try{await downloadElementPdf(x,filename,{padding:"12mm",margin:"12mm"})}finally{setBusy(null)}}async function print(){const x=el();if(!x)return window.print();setBusy("print");try{await printElement(x,{title:filename.replace(/\.pdf$/,"") ,margin:"12mm"})}finally{setBusy(null)}}
 return <div className="min-h-screen bg-white"><div className="no-print sticky top-0 z-10 border-b bg-card/80"><div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-3 px-4 py-3"><Button asChild variant="ghost"><Link to="/admin/$id" params={{id:order.id}}><ArrowLeft className="mr-2 h-4 w-4"/>Voltar à edição</Link></Button><div className="flex gap-2"><Button onClick={()=>void pdf()} disabled={busy!==null}>{busy==="pdf"?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Download className="mr-2 h-4 w-4"/>}Baixar PDF</Button><Button variant="outline" onClick={()=>void print()} disabled={busy!==null}><Printer className="mr-2 h-4 w-4"/>Imprimir</Button></div></div></div>
 <main className="flex justify-center py-8 print:py-0"><article className="a4-checklist bg-white text-black" style={{width:"210mm",minHeight:"297mm",padding:"12mm",fontFamily:"Arial, Helvetica, sans-serif",fontSize:"12px",lineHeight:1.4}}>
 <header className="mb-3 flex items-start justify-between border-b-2 border-black pb-2"><div className="flex items-center gap-3"><img src={logo} alt="LHL Festas" className="w-11"/><div><p className="text-[18px] font-bold">LHL Festas</p><p className="text-[12px] font-semibold">Checklist Operacional de Entrega e Retorno</p></div></div><div className="text-right text-[10px]"><b>Contrato</b><p className="font-mono">{order.id.slice(0,8).toUpperCase()}</p><b>Impresso</b><p>{new Date().toLocaleDateString("pt-BR")}</p></div></header>
 <section className="mb-3 grid grid-cols-3 gap-3"><div><h2 className="mb-1 border-b border-black font-bold uppercase">Decoração</h2>{d?.fotoDecoracaoUrl?<div className="flex h-36 items-center justify-center overflow-hidden border"><img src={d.fotoDecoracaoUrl} crossOrigin="anonymous" className="max-h-full max-w-full object-contain"/></div>:<div className="flex h-36 items-center justify-center border border-dashed">Foto não cadastrada</div>}</div><div className="col-span-2"><h2 className="mb-1 border-b border-black font-bold uppercase">Festa</h2><table className="w-full"><tbody>{[["Cliente",order.nome],["Telefone",order.telefone],["Aniversariante",d?.nomeAniversariante],["Idade",d?.idadeAniversariante],["Tipo",d?.tipoFesta],["Tema",order.tema],["Modalidade",order.modalidade],["Kit",order.plano],["Evento",formatDateBR(d?.dataEvento)],...(!isMontagem?[["Retirada",formatDateTimeBR(d?.dataRetirada,d?.horaRetirada)],["Devolução",formatDateTimeBR(d?.dataDevolucao,d?.horaDevolucao)]]:[])].map(([k,v])=><tr key={String(k)}><th className="w-[35%] pr-2 text-left">{k}</th><td>{v||"—"}</td></tr>)}</tbody></table>{kitItensChecklist.length>0&&<div className="mt-2"><b>Itens inclusos no kit</b><ul className="list-disc pl-5">{kitItensChecklist.map(i=><li key={i}>{i}</li>)}</ul></div>}</div></section>
 <section className="mb-3 border-2 border-black p-2"><h2 className="mb-2 border-b border-black pb-1 font-bold uppercase">Resumo Financeiro</h2><table className="w-full"><tbody><tr><th className="text-left">Valor total contratado</th><td className="text-right">{fmt(pagamento.valorTotal)}</td></tr><tr><th className="text-left">Recebido até agora</th><td className="text-right">{fmt(pagamento.totalRecebido)}</td></tr><tr><th className="text-left">Saldo pendente</th><td className="text-right font-bold">{fmt(pagamento.saldoReceber)}</td></tr><tr><th className="text-left">Caução</th><td className="text-right">{isMontagem?"ISENTO":d?.caucaoRecebida==="Sim"?"RECEBIDA":fmt(Number(String(d?.valorCaucao||0).replace(",","."))||0)}</td></tr></tbody></table><p className="mt-2 border-t-2 border-black pt-2 text-center text-[13px] font-bold uppercase">{pagamento.saldoReceber<=0.009?"Pagamento: QUITADO":"Pagamento: SALDO PENDENTE"}</p></section>
 {d?.observacoesInternas&&<section className="mb-3 border-2 border-black p-2"><b className="uppercase">Atenção / Observações</b><p className="whitespace-pre-wrap">{d.observacoesInternas}</p></section>}
 {structures.length>0&&<section className="mb-3"><h2 className="mb-2 border-b-2 border-black font-bold uppercase">Estruturas — Conferência</h2>{structures.map((s,i)=>{const total=s.qty*s.model.pecas;return <div key={i} className="mb-2 border border-black p-2"><b>{s.model.nome}</b><p>{s.qty} estrutura(s) · {s.model.pecas} peças cada · total esperado {total}</p><div className="mt-2 grid grid-cols-3 gap-2"><div className="border p-2">Saída: {blank}</div><div className="border p-2">Retorno: {blank}</div><div className="border p-2">Diferença: {blank}</div></div></div>})}</section>}
 {excItems.length>0&&<section className="mb-3"><h2 className="mb-2 border-b-2 border-black font-bold uppercase">Itens Exclusivos Reservados</h2><table className="w-full border-collapse"><thead><tr><th className="border p-1 text-left">Categoria</th><th className="border p-1 text-left">Item</th><th className="border p-1">Saída</th><th className="border p-1">Retorno</th></tr></thead><tbody>{excItems.map((it:any)=><tr key={it.id}><td className="border p-1">{CATEGORY_LABELS[it.categoria]}</td><td className="border p-1">{it.nome}{it.aComprarSpec?` — ${it.aComprarSpec}`:""}</td><td className="border p-1 text-center">☐</td><td className="border p-1 text-center">☐</td></tr>)}</tbody></table></section>}
 <section className="mb-3"><h2 className="mb-2 border-b-2 border-black font-bold uppercase">Itens do Kit</h2>{GROUP_ORDER.filter(g=>grouped[g].length).map(g=><div key={g} className="mb-2"><p className="bg-black px-2 text-white font-bold">{g}</p><table className="w-full border-collapse"><tbody>{grouped[g].map((it,i)=><tr key={i}><td className="border p-1">{it.label}</td><td className="w-20 border p-1 text-center">{it.qty}</td><td className="w-20 border p-1 text-center">Saída ☐</td><td className="w-20 border p-1 text-center">Retorno ☐</td></tr>)}</tbody></table></div>)}</section>
 <section className="mb-3 grid grid-cols-2 gap-3"><div className="border-2 border-black p-2"><b className="uppercase">Conferência de Saída</b><p>☐ KIT COMPLETO</p><p>☐ KIT COM DIVERGÊNCIA</p><p className="mt-2">Responsável: {blank}</p></div><div className="border-2 border-black p-2"><b className="uppercase">Conferência de Retorno</b><p>☐ KIT COMPLETO</p><p>☐ KIT COM DIVERGÊNCIA</p><p className="mt-2">Responsável: {blank}</p></div></section>
 <footer className="mt-4 border-t border-black pt-2 text-center text-[9px] font-bold uppercase tracking-[.2em]">LHL Festas</footer>
 </article></main></div>
}
