/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConsultorRouteImport } from './routes/consultor'
import { Route as HeavenRouteImport } from './routes/heaven'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as OrcamentoObrigadoRouteImport } from './routes/orcamento-obrigado'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as AdminContratosRouteImport } from './routes/admin.contratos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminGestaoRouteImport } from './routes/admin.gestao'
import { Route as AdminHeavenLeadsRouteImport } from './routes/admin.heaven-leads'
import { Route as AdminItensExclusivosRouteImport } from './routes/admin.itens-exclusivos'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminPatrimonioRouteImport } from './routes/admin.patrimonio'
import { Route as ChecklistIdRouteImport } from './routes/checklist.$id'
import { Route as ContractIdRouteImport } from './routes/contract.$id'
import { Route as AdminProducaoIndexRouteImport } from './routes/admin.producao.index'
import { Route as AdminProducaoIdRouteImport } from './routes/admin.producao.$id'
import { Route as AdminSolicitacoesIndexRouteImport } from './routes/admin.solicitacoes.index'
import { Route as AdminSolicitacoesIdRouteImport } from './routes/admin.solicitacoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorRoute = ConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => rootRouteImport,
} as any)
const HeavenRoute = HeavenRouteImport.update({
  id: '/heaven',
  path: '/heaven',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoObrigadoRoute = OrcamentoObrigadoRouteImport.update({
  id: '/orcamento-obrigado',
  path: '/orcamento-obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosRoute = AdminContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestaoRoute = AdminGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeavenLeadsRoute = AdminHeavenLeadsRouteImport.update({
  id: '/heaven-leads',
  path: '/heaven-leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItensExclusivosRoute = AdminItensExclusivosRouteImport.update({
  id: '/itens-exclusivos',
  path: '/itens-exclusivos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatrimonioRoute = AdminPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AdminRoute,
} as any)
const ChecklistIdRoute = ChecklistIdRouteImport.update({
  id: '/checklist/$id',
  path: '/checklist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractIdRoute = ContractIdRouteImport.update({
  id: '/contract/$id',
  path: '/contract/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProducaoIndexRoute = AdminProducaoIndexRouteImport.update({
  id: '/producao/',
  path: '/producao/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProducaoIdRoute = AdminProducaoIdRouteImport.update({
  id: '/producao/$id',
  path: '/producao/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesIndexRoute = AdminSolicitacoesIndexRouteImport.update({
  id: '/solicitacoes/',
  path: '/solicitacoes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesIdRoute = AdminSolicitacoesIdRouteImport.update({
  id: '/solicitacoes/$id',
  path: '/solicitacoes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/consultor': typeof ConsultorRoute
  '/heaven': typeof HeavenRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/orcamento-obrigado': typeof OrcamentoObrigadoRoute
  '/reserva': typeof ReservaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/contratos': typeof AdminContratosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin/heaven-leads': typeof AdminHeavenLeadsRoute
  '/admin/itens-exclusivos': typeof AdminItensExclusivosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/patrimonio': typeof AdminPatrimonioRoute
  '/checklist/$id': typeof ChecklistIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/producao/$id': typeof AdminProducaoIdRoute
  '/admin/solicitacoes/$id': typeof AdminSolicitacoesIdRoute
  '/admin/producao/': typeof AdminProducaoIndexRoute
  '/admin/solicitacoes/': typeof AdminSolicitacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consultor': typeof ConsultorRoute
  '/heaven': typeof HeavenRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/orcamento-obrigado': typeof OrcamentoObrigadoRoute
  '/reserva': typeof ReservaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/contratos': typeof AdminContratosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin/heaven-leads': typeof AdminHeavenLeadsRoute
  '/admin/itens-exclusivos': typeof AdminItensExclusivosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/patrimonio': typeof AdminPatrimonioRoute
  '/checklist/$id': typeof ChecklistIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/producao/$id': typeof AdminProducaoIdRoute
  '/admin/solicitacoes/$id': typeof AdminSolicitacoesIdRoute
  '/admin/producao': typeof AdminProducaoIndexRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/consultor': typeof ConsultorRoute
  '/heaven': typeof HeavenRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/orcamento': typeof OrcamentoRoute
  '/orcamento-obrigado': typeof OrcamentoObrigadoRoute
  '/reserva': typeof ReservaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/contratos': typeof AdminContratosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/gestao': typeof AdminGestaoRoute
  '/admin/heaven-leads': typeof AdminHeavenLeadsRoute
  '/admin/itens-exclusivos': typeof AdminItensExclusivosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/patrimonio': typeof AdminPatrimonioRoute
  '/checklist/$id': typeof ChecklistIdRoute
  '/contract/$id': typeof ContractIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/producao/$id': typeof AdminProducaoIdRoute
  '/admin/solicitacoes/$id': typeof AdminSolicitacoesIdRoute
  '/admin/producao/': typeof AdminProducaoIndexRoute
  '/admin/solicitacoes/': typeof AdminSolicitacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/consultor'
    | '/heaven'
    | '/login'
    | '/obrigado'
    | '/orcamento'
    | '/orcamento-obrigado'
    | '/reserva'
    | '/sitemap.xml'
    | '/admin/$id'
    | '/admin/contratos'
    | '/admin/financeiro'
    | '/admin/gestao'
    | '/admin/heaven-leads'
    | '/admin/itens-exclusivos'
    | '/admin/leads'
    | '/admin/patrimonio'
    | '/checklist/$id'
    | '/contract/$id'
    | '/admin/'
    | '/admin/producao/$id'
    | '/admin/solicitacoes/$id'
    | '/admin/producao/'
    | '/admin/solicitacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/consultor'
    | '/heaven'
    | '/login'
    | '/obrigado'
    | '/orcamento'
    | '/orcamento-obrigado'
    | '/reserva'
    | '/sitemap.xml'
    | '/admin/$id'
    | '/admin/contratos'
    | '/admin/financeiro'
    | '/admin/gestao'
    | '/admin/heaven-leads'
    | '/admin/itens-exclusivos'
    | '/admin/leads'
    | '/admin/patrimonio'
    | '/checklist/$id'
    | '/contract/$id'
    | '/admin'
    | '/admin/producao/$id'
    | '/admin/solicitacoes/$id'
    | '/admin/producao'
    | '/admin/solicitacoes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/consultor'
    | '/heaven'
    | '/login'
    | '/obrigado'
    | '/orcamento'
    | '/orcamento-obrigado'
    | '/reserva'
    | '/sitemap.xml'
    | '/admin/$id'
    | '/admin/contratos'
    | '/admin/financeiro'
    | '/admin/gestao'
    | '/admin/heaven-leads'
    | '/admin/itens-exclusivos'
    | '/admin/leads'
    | '/admin/patrimonio'
    | '/checklist/$id'
    | '/contract/$id'
    | '/admin/'
    | '/admin/producao/$id'
    | '/admin/solicitacoes/$id'
    | '/admin/producao/'
    | '/admin/solicitacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsultorRoute: typeof ConsultorRoute
  HeavenRoute: typeof HeavenRoute
  LoginRoute: typeof LoginRoute
  ObrigadoRoute: typeof ObrigadoRoute
  OrcamentoRoute: typeof OrcamentoRoute
  OrcamentoObrigadoRoute: typeof OrcamentoObrigadoRoute
  ReservaRoute: typeof ReservaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ChecklistIdRoute: typeof ChecklistIdRoute
  ContractIdRoute: typeof ContractIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor': {
      id: '/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof ConsultorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heaven': {
      id: '/heaven'
      path: '/heaven'
      fullPath: '/heaven'
      preLoaderRoute: typeof HeavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento-obrigado': {
      id: '/orcamento-obrigado'
      path: '/orcamento-obrigado'
      fullPath: '/orcamento-obrigado'
      preLoaderRoute: typeof OrcamentoObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos': {
      id: '/admin/contratos'
      path: '/contratos'
      fullPath: '/admin/contratos'
      preLoaderRoute: typeof AdminContratosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gestao': {
      id: '/admin/gestao'
      path: '/gestao'
      fullPath: '/admin/gestao'
      preLoaderRoute: typeof AdminGestaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/heaven-leads': {
      id: '/admin/heaven-leads'
      path: '/heaven-leads'
      fullPath: '/admin/heaven-leads'
      preLoaderRoute: typeof AdminHeavenLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/itens-exclusivos': {
      id: '/admin/itens-exclusivos'
      path: '/itens-exclusivos'
      fullPath: '/admin/itens-exclusivos'
      preLoaderRoute: typeof AdminItensExclusivosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patrimonio': {
      id: '/admin/patrimonio'
      path: '/patrimonio'
      fullPath: '/admin/patrimonio'
      preLoaderRoute: typeof AdminPatrimonioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checklist/$id': {
      id: '/checklist/$id'
      path: '/checklist/$id'
      fullPath: '/checklist/$id'
      preLoaderRoute: typeof ChecklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$id': {
      id: '/contract/$id'
      path: '/contract/$id'
      fullPath: '/contract/$id'
      preLoaderRoute: typeof ContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/producao/': {
      id: '/admin/producao/'
      path: '/producao'
      fullPath: '/admin/producao/'
      preLoaderRoute: typeof AdminProducaoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/producao/$id': {
      id: '/admin/producao/$id'
      path: '/producao/$id'
      fullPath: '/admin/producao/$id'
      preLoaderRoute: typeof AdminProducaoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes/': {
      id: '/admin/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes/'
      preLoaderRoute: typeof AdminSolicitacoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes/$id': {
      id: '/admin/solicitacoes/$id'
      path: '/solicitacoes/$id'
      fullPath: '/admin/solicitacoes/$id'
      preLoaderRoute: typeof AdminSolicitacoesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIdRoute: typeof AdminIdRoute
  AdminContratosRoute: typeof AdminContratosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminGestaoRoute: typeof AdminGestaoRoute
  AdminHeavenLeadsRoute: typeof AdminHeavenLeadsRoute
  AdminItensExclusivosRoute: typeof AdminItensExclusivosRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPatrimonioRoute: typeof AdminPatrimonioRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProducaoIdRoute: typeof AdminProducaoIdRoute
  AdminSolicitacoesIdRoute: typeof AdminSolicitacoesIdRoute
  AdminProducaoIndexRoute: typeof AdminProducaoIndexRoute
  AdminSolicitacoesIndexRoute: typeof AdminSolicitacoesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIdRoute: AdminIdRoute,
  AdminContratosRoute: AdminContratosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminGestaoRoute: AdminGestaoRoute,
  AdminHeavenLeadsRoute: AdminHeavenLeadsRoute,
  AdminItensExclusivosRoute: AdminItensExclusivosRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPatrimonioRoute: AdminPatrimonioRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProducaoIdRoute: AdminProducaoIdRoute,
  AdminSolicitacoesIdRoute: AdminSolicitacoesIdRoute,
  AdminProducaoIndexRoute: AdminProducaoIndexRoute,
  AdminSolicitacoesIndexRoute: AdminSolicitacoesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsultorRoute: ConsultorRoute,
  HeavenRoute: HeavenRoute,
  LoginRoute: LoginRoute,
  ObrigadoRoute: ObrigadoRoute,
  OrcamentoRoute: OrcamentoRoute,
  OrcamentoObrigadoRoute: OrcamentoObrigadoRoute,
  ReservaRoute: ReservaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ChecklistIdRoute: ChecklistIdRoute,
  ContractIdRoute: ContractIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
